import {
  login,
  logout,
  register,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
} from './userActions'
import {
  saveCategory,
  CATEGORY_CREATE_BEGIN,
  CATEGORY_CREATE_SUCCESS,
  CATEGORY_CREATE_FAILURE,
  CATEGORY_UPDATE_BEGIN,
  CATEGORY_UPDATE_SUCCESS,
  CATEGORY_UPDATE_FAILURE,
} from './categoryActions'
import {
  changeCollection,
  saveCollection,
  deleteCollection,
  COLLECTION_CHANGED,
  COLLECTION_CREATE_BEGIN,
  COLLECTION_CREATE_SUCCESS,
  COLLECTION_CREATE_FAILURE,
  COLLECTION_UPDATE_BEGIN,
  COLLECTION_UPDATE_SUCCESS,
  COLLECTION_UPDATE_FAILURE,
  COLLECTION_DELETE_BEGIN,
  COLLECTION_DELETE_SUCCESS,
  COLLECTION_DELETE_FAILURE
} from './collectionActions'

export {
  changeCollection,
  saveCategory,
  saveCollection,
  deleteCollection,
  login,
  logout,
  register,
  CATEGORY_CREATE_BEGIN,
  CATEGORY_CREATE_SUCCESS,
  CATEGORY_CREATE_FAILURE,
  CATEGORY_UPDATE_BEGIN,
  CATEGORY_UPDATE_SUCCESS,
  CATEGORY_UPDATE_FAILURE,
  COLLECTION_CHANGED,
  COLLECTION_CREATE_BEGIN,
  COLLECTION_CREATE_SUCCESS,
  COLLECTION_CREATE_FAILURE,
  COLLECTION_UPDATE_BEGIN,
  COLLECTION_UPDATE_SUCCESS,
  COLLECTION_UPDATE_FAILURE,
  COLLECTION_DELETE_BEGIN,
  COLLECTION_DELETE_SUCCESS,
  COLLECTION_DELETE_FAILURE,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
}